# Generated by Django 3.2.9 on 2021-12-16 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_name_staff_staffname'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auctions.user'),
            preserve_default=False,
        ),
    ]
