# Generated by Django 3.2.9 on 2021-12-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_staff_staff_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='startprice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
