# Generated by Django 3.2.9 on 2021-12-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20211218_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositions',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
