# Generated by Django 3.2.9 on 2021-12-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_propositions_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image_one',
            field=models.ImageField(height_field='200', upload_to='', width_field='100'),
        ),
    ]
