# Generated by Django 3.2.9 on 2021-12-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20211221_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image_one',
            field=models.ImageField(blank=True, default='staff/F-208_H.png', null=True, upload_to='staff/'),
        ),
    ]
